# Generated by Django 4.2.16 on 2024-10-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanceProfile',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('danceability', models.FloatField(max_length=100)),
                ('energy', models.FloatField(max_length=100)),
                ('mode', models.IntegerField(max_length=100)),
                ('acousticness', models.FloatField(max_length=100)),
                ('tempo', models.FloatField(max_length=100)),
                ('duration_ms', models.IntegerField(max_length=100)),
                ('num_sections', models.IntegerField(max_length=100)),
                ('num_segments', models.IntegerField(max_length=100)),
            ],
        ),
    ]
